[package]
name = "dslib"
version = "0.0.1"
authors = []
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi-derive = "1.1.0"
napi = { version = "1.7.5", features = ["serde-json"] }
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
napi-build = "1.1.0"

# libc = "0.2"
# nodejs-sys = "0.13.0"

# serde_json = "1.0.64"

[target.'cfg(windows)'.build-dependencies]
# windows dependencies

[target.'cfg(unix)'.build-dependencies]
# unix dependencies