[package]
name = "dslib"
version = "0.0.1"
authors = []
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi-derive = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
napi = { version = "1.7.5", features = ["serde-json"] }

[build-dependencies]
napi-build = "1.1.0"

[target.'cfg(windows)'.build-dependencies]
# windows dependencies

[target.'cfg(unix)'.build-dependencies]
# unix dependencies